version: '3.8'

services:

  nginx:
    build: nginx
    ports:
      - 8080:8080

  app:
    build: app
    restart: always
    env_file: .env
    volumes:
      - ./app/src:/usr/src/app
      - /usr/src/app/node_modules
    entrypoint: dockerize -wait tcp://db:3306 -timeout 50s node /usr/src/app

  db:
    build: db
    restart: always
    env_file: .env
    volumes:
      - ./db/data:/var/lib/mysql
